import type { NextConfig } from "next";
import path from "node:path";

const nextConfig: NextConfig = {
  turbopack: {
    root: path.resolve(__dirname),
  },
  async redirects() {
    return [
      { source: "/login", destination: "/connexion", permanent: true },
      { source: "/forgot-password", destination: "/mot-de-passe-oublie", permanent: true },
      { source: "/reset-password", destination: "/reinitialiser-mot-de-passe", permanent: true },
      { source: "/simulate", destination: "/simulateurs", permanent: true },
      { source: "/simulate/net-gross", destination: "/simulateurs/brut-net", permanent: true },
      {
        source: "/simulate/employer-total-cost",
        destination: "/simulateurs/cout-employeur-total",
        permanent: true,
      },
      { source: "/simulate/annual-income-tax", destination: "/simulateurs/ir-annuel", permanent: true },
      { source: "/simulate/licenciement", destination: "/simulateurs/licenciement", permanent: true },
      { source: "/simulate/demission", destination: "/simulateurs/demission", permanent: true },
      { source: "/simulate/duree-preavis", destination: "/simulateurs/duree-preavis", permanent: true },
      { source: "/simulate/fin-cdd", destination: "/simulateurs/fin-cdd", permanent: true },
      {
        source: "/simulate/probation-termination",
        destination: "/simulateurs/rupture-periode-essai",
        permanent: true,
      },
      {
        source: "/simulate/seniority-growth",
        destination: "/simulateurs/progression-anciennete",
        permanent: true,
      },
      {
        source: "/simulate/leave-accrual",
        destination: "/simulateurs/acquisition-conges",
        permanent: true,
      },
      { source: "/simulate/smig-compliance", destination: "/simulateurs/conformite-smig", permanent: true },
      { source: "/simulate/overtime", destination: "/simulateurs/heures-supplementaires", permanent: true },
      {
        source: "/simulate/public-holiday-compensation",
        destination: "/simulateurs/compensation-jours-feries",
        permanent: true,
      },
      { source: "/simulate/maternity-leave", destination: "/simulateurs/conge-maternite", permanent: true },
      { source: "/simulate/sick-leave", destination: "/simulateurs/conge-maladie", permanent: true },
      { source: "/simulate/cnss-pension", destination: "/simulateurs/pension-cnss", permanent: true },
      { source: "/simulate/work-accident", destination: "/simulateurs/accident-travail", permanent: true },
      {
        source: "/simulate/harassment-scenario",
        destination: "/simulateurs/scenario-harcelement",
        permanent: true,
      },
      {
        source: "/simulate/unpaid-salary-recovery",
        destination: "/simulateurs/recouvrement-salaire-impaye",
        permanent: true,
      },
      {
        source: "/simulate/unpaid-overtime-recovery",
        destination: "/simulateurs/recouvrement-heures-supplementaires",
        permanent: true,
      },
      { source: "/tools", destination: "/outils", permanent: true },
      { source: "/tools/payslip-detector", destination: "/outils/detecteur-fiche-paie", permanent: true },
      { source: "/tools/salary-delay-alert", destination: "/outils/alerte-retard-salaire", permanent: true },
      {
        source: "/tools/compliance-risk-score",
        destination: "/outils/score-risque-conformite",
        permanent: true,
      },
      {
        source: "/tools/final-settlement-audit",
        destination: "/outils/audit-solde-tout-compte",
        permanent: true,
      },
      {
        source: "/tools/disciplinary-procedure-check",
        destination: "/outils/controle-procedure-disciplinaire",
        permanent: true,
      },
      {
        source: "/tools/fixed-term-contract-risk",
        destination: "/outils/risque-requalification-cdd",
        permanent: true,
      },
      {
        source: "/tools/pre-litigation-timeline",
        destination: "/outils/feuille-route-pre-contentieux",
        permanent: true,
      },
    ];
  },
  async rewrites() {
    return [
      { source: "/connexion", destination: "/login" },
      { source: "/mot-de-passe-oublie", destination: "/forgot-password" },
      { source: "/reinitialiser-mot-de-passe", destination: "/reset-password" },
      { source: "/salaire/brut-net", destination: "/simulateurs/brut-net" },
      { source: "/salaire/ir-igr", destination: "/simulateurs/ir-annuel" },
      { source: "/salaire/prime-bonus", destination: "/planifier/simulation-prime" },
      { source: "/salaire/avantages-nature", destination: "/planifier/avantages-nature" },
      { source: "/salaire/smig-smag", destination: "/simulateurs/conformite-smig" },
      { source: "/salaire/bulletin-paie", destination: "/planifier/bulletin-paie" },
      { source: "/salaire/optimisation-remuneration", destination: "/planifier/optimisation-remuneration" },
      { source: "/contrat-depart/licenciement", destination: "/simulateurs/licenciement" },
      { source: "/contrat-depart/demission", destination: "/simulateurs/demission" },
      { source: "/contrat-depart/duree-preavis", destination: "/simulateurs/duree-preavis" },
      { source: "/contrat-depart/fin-cdd", destination: "/simulateurs/fin-cdd" },
      { source: "/contrat-depart/periode-essai", destination: "/simulateurs/rupture-periode-essai" },
      { source: "/contrat-depart/anciennete-indemnites", destination: "/simulateurs/progression-anciennete" },
      { source: "/contrat-depart/lettre-demission", destination: "/documents/resignation-letter" },
      { source: "/contrat-depart/lettre-preavis", destination: "/documents/notice-letter" },
      { source: "/contrat-depart/rupture-amiable", destination: "/documents/mutual-termination-proposal" },
      { source: "/contrat-depart/certificat-travail", destination: "/documents/employment-certificate-request" },
      { source: "/conges-cnss/conges-acquis", destination: "/simulateurs/acquisition-conges" },
      { source: "/conges-cnss/heures-supplementaires", destination: "/simulateurs/heures-supplementaires" },
      { source: "/conges-cnss/jour-ferie", destination: "/simulateurs/compensation-jours-feries" },
      { source: "/conges-cnss/arret-maladie", destination: "/simulateurs/conge-maladie" },
      { source: "/conges-cnss/conge-maternite", destination: "/simulateurs/conge-maternite" },
      { source: "/conges-cnss/conge-sans-solde", destination: "/documents/unpaid-leave-request" },
      { source: "/conges-cnss/pension-cnss", destination: "/simulateurs/pension-cnss" },
      { source: "/conges-cnss/indemnite-chomage", destination: "/planifier/indemnite-chomage" },
      { source: "/conges-cnss/retraite-cnss", destination: "/planifier/retraite-avancee" },
      { source: "/conges-cnss/accident-travail", destination: "/simulateurs/accident-travail" },
      { source: "/conges-cnss/reclamation-cnss", destination: "/documents/cnss-complaint-letter" },
      { source: "/litiges/salaire-impaye", destination: "/simulateurs/recouvrement-salaire-impaye" },
      { source: "/litiges/heures-sup-impayees", destination: "/simulateurs/recouvrement-heures-supplementaires" },
      { source: "/litiges/harcelement", destination: "/simulateurs/scenario-harcelement" },
      { source: "/litiges/reclamation-employeur", destination: "/documents/formal-complaint-employer" },
      { source: "/litiges/inspection-travail", destination: "/documents/labor-inspector-complaint" },
      { source: "/litiges/pre-contentieux", destination: "/outils/feuille-route-pre-contentieux" },
      { source: "/litiges/solde-tout-compte", destination: "/outils/audit-solde-tout-compte" },
      { source: "/litiges/procedure-disciplinaire", destination: "/outils/controle-procedure-disciplinaire" },
      { source: "/modeles/tous", destination: "/documents" },
      { source: "/rh-pro/cout-employeur-total", destination: "/simulateurs/cout-employeur-total" },
      { source: "/rh-pro/masse-salariale", destination: "/planifier/masse-salariale" },
      { source: "/rh-pro/cout-recrutement", destination: "/planifier/cout-recrutement" },
      { source: "/carriere/comparaison-scenarios", destination: "/planifier/comparaison-scenarios" },
      { source: "/carriere/augmentation-salaire", destination: "/planifier/augmentation-salaire" },
      { source: "/carriere/promotion", destination: "/planifier/scenario-promotion" },
      { source: "/carriere/freelance-vs-salarie", destination: "/planifier/freelance-vs-salarie" },
      { source: "/carriere/capacite-credit", destination: "/planifier/capacite-credit" },
      { source: "/carriere/auto-entrepreneur", destination: "/planifier/auto-entrepreneur" },
      { source: "/carriere/tarification-freelance", destination: "/planifier/tarification-freelance" },
      { source: "/carriere/benefice-net", destination: "/planifier/benefice-net" },
      { source: "/simulateurs", destination: "/simulate" },
      { source: "/simulateurs/brut-net", destination: "/simulate/net-gross" },
      { source: "/simulateurs/cout-employeur-total", destination: "/simulate/employer-total-cost" },
      { source: "/simulateurs/ir-annuel", destination: "/simulate/annual-income-tax" },
      { source: "/simulateurs/licenciement", destination: "/simulate/licenciement" },
      { source: "/simulateurs/demission", destination: "/simulate/demission" },
      { source: "/simulateurs/duree-preavis", destination: "/simulate/duree-preavis" },
      { source: "/simulateurs/fin-cdd", destination: "/simulate/fin-cdd" },
      { source: "/simulateurs/rupture-periode-essai", destination: "/simulate/probation-termination" },
      { source: "/simulateurs/progression-anciennete", destination: "/simulate/seniority-growth" },
      { source: "/simulateurs/acquisition-conges", destination: "/simulate/leave-accrual" },
      { source: "/simulateurs/conformite-smig", destination: "/simulate/smig-compliance" },
      { source: "/simulateurs/heures-supplementaires", destination: "/simulate/overtime" },
      {
        source: "/simulateurs/compensation-jours-feries",
        destination: "/simulate/public-holiday-compensation",
      },
      { source: "/simulateurs/conge-maternite", destination: "/simulate/maternity-leave" },
      { source: "/simulateurs/conge-maladie", destination: "/simulate/sick-leave" },
      { source: "/simulateurs/pension-cnss", destination: "/simulate/cnss-pension" },
      { source: "/simulateurs/accident-travail", destination: "/simulate/work-accident" },
      { source: "/simulateurs/scenario-harcelement", destination: "/simulate/harassment-scenario" },
      {
        source: "/simulateurs/recouvrement-salaire-impaye",
        destination: "/simulate/unpaid-salary-recovery",
      },
      {
        source: "/simulateurs/recouvrement-heures-supplementaires",
        destination: "/simulate/unpaid-overtime-recovery",
      },
      { source: "/simulateurs/:slug/result", destination: "/simulate/:slug/result" },
      { source: "/planifier/:slug/result", destination: "/planifier/[slug]/result" },
      { source: "/salaire/:slug/result", destination: "/salaire/[slug]/result" },
      { source: "/rh-pro/:slug/result", destination: "/rh-pro/[slug]/result" },
      { source: "/conges-cnss/:slug/result", destination: "/conges-cnss/[slug]/result" },
      { source: "/contrat-depart/:slug/result", destination: "/contrat-depart/[slug]/result" },
      { source: "/litiges/:slug/result", destination: "/litiges/[slug]/result" },
      { source: "/outils", destination: "/tools" },
      { source: "/outils/detecteur-fiche-paie", destination: "/tools/payslip-detector" },
      { source: "/outils/alerte-retard-salaire", destination: "/tools/salary-delay-alert" },
      { source: "/outils/score-risque-conformite", destination: "/tools/compliance-risk-score" },
      { source: "/outils/audit-solde-tout-compte", destination: "/tools/final-settlement-audit" },
      {
        source: "/outils/controle-procedure-disciplinaire",
        destination: "/tools/disciplinary-procedure-check",
      },
      { source: "/outils/risque-requalification-cdd", destination: "/tools/fixed-term-contract-risk" },
      { source: "/outils/feuille-route-pre-contentieux", destination: "/tools/pre-litigation-timeline" },
    ];
  },
};

export default nextConfig;
